# Generated by Django 4.2.5 on 2023-09-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin Acct"),
                            ("technical", "Technical Acct"),
                            ("user", "User Acct"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("account_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "ticket_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ticket_created", models.DateTimeField(auto_now_add=True)),
                ("ticket_details", models.CharField(max_length=200)),
                (
                    "branches",
                    models.CharField(
                        choices=[
                            ("Juan Sumulong Campus", "Juan Sumulong"),
                            ("Apolinario Mabini Campus", "Apolinario Mabini"),
                            ("Andres Bonifacio Campus", "Andres Bonifacio"),
                            ("Jose Abad Campus", "Jose Abad"),
                            ("Jose Rizal Campus", "Jose Rizal"),
                            ("Elisa Esguerra Campus", "Elisa Esguerra"),
                            ("Plaridel Campus", "Plaridel"),
                        ],
                        default="Juan Sumulong Campus",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Ongoing", "On Going"),
                            ("Complete", "Complete"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("software", "Software"),
                            ("hardware", "Hardware"),
                            ("connection", "Connection"),
                        ],
                        default="software",
                        max_length=10,
                    ),
                ),
                ("problem", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "account_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crud_app.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=50)),
                ("equipments", models.CharField(max_length=100)),
                ("details", models.CharField(blank=True, max_length=50)),
                (
                    "ticket_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crud_app.ticket",
                    ),
                ),
            ],
        ),
    ]
